version: '3'

services:
  server:
    container_name: city-and-state-crud-api
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
      MONGO_DB: 'mongodb://db:27017/city-and-state-crud'
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: city-and-state-crud-db
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db